export const ROOMS = [
  {
    id: "emerald-12-a",
    tower: "Emerald Tower",
    level: "Level 12",
    name: "Meeting Room A",
    code: "EM-12-A",
    capacity: 8,
    type: "meeting",
    status: "available",
    availability: "Available until 3:00 PM",
    amenities: [
      "Projector",
      "TV",
      "Whiteboard",
      "Video Conference",
    ],
  },

  {
    id: "emerald-12-b",
    tower: "Emerald Tower",
    level: "Level 12",
    name: "Discussion Room B",
    code: "EM-12-B",
    capacity: 4,
    type: "discussion",
    status: "occupied",
    availability: "Busy until 1:30 PM",
    amenities: [
      "Monitor",
      "Speaker",
      "Glass Board",
    ],
  },

  {
    id: "sapphire-15-training",
    tower: "Sapphire Tower",
    level: "Level 15",
    name: "Training Room",
    code: "SP-15-TR",
    capacity: 20,
    type: "training",
    status: "reserved",
    availability: "Reserved at 2:00 PM",
    amenities: [
      "Projector",
      "Microphone",
      "Stage",
      "PA System",
    ],
  },

  {
    id: "ruby-05-focus",
    tower: "Ruby Tower",
    level: "Level 5",
    name: "Focus Pod",
    code: "RB-05-FP",
    capacity: 2,
    type: "focus",
    status: "maintenance",
    availability: "Unavailable temporarily",
    amenities: [
      "Quiet Zone",
      "Charging Port",
    ],
  },

  {
    id: "emerald-08-board",
    tower: "Emerald Tower",
    level: "Level 8",
    name: "Board Room",
    code: "EM-08-BR",
    capacity: 14,
    type: "board",
    status: "available",
    availability: "Available all day",
    amenities: [
      "Dual Display",
      "Conference Camera",
      "Coffee Area",
      "Video Conference",
    ],
  },

  {
    id: "sapphire-10-huddle",
    tower: "Sapphire Tower",
    level: "Level 10",
    name: "Huddle Space",
    code: "SP-10-HS",
    capacity: 6,
    type: "huddle",
    status: "occupied",
    availability: "Busy until 5:00 PM",
    amenities: [
      "TV",
      "Whiteboard",
      "Standing Desk",
    ],
  },
] as const;